### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by blattersturm** [CamxxCore/PauseMenuHelper#2]
Hello!

I'm writing this on behalf of the [CitizenFX Collective](https://github.com/citizenfx), developers of the [FiveM](https://fivem.net) modification framework for GTA V, which you have definitely heard of given your gratuitous reuse of some of our RAGE framework code. 😛 

We've noticed your repository [doesn't contain any license](https://choosealicense.com/no-license/) whatsoever, which means that we can not reuse the code from this modification in our framework at all - is this intentional?

If not, please consider adding a license to your repository. 💓 

Thanks in advance,

guava

**Comment by CamxxCore** [comment]
Hi there. It's not intended, no. I will add a license. And yes I am familiar with FiveM :D I am already a big fan (: You guys have done some really incredible work!!!
